USE zync;

ALTER TABLE usuarios
  ADD COLUMN foto_url VARCHAR(500) NULL,
  ADD COLUMN idade INT NULL,
  ADD COLUMN cpf VARCHAR(14) NULL,
  ADD COLUMN instagram VARCHAR(120) NULL,
  ADD COLUMN facebook VARCHAR(120) NULL,
  ADD COLUMN telefone VARCHAR(20) NULL;

CREATE TABLE IF NOT EXISTS mensagens_suporte (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT NOT NULL,
  mensagem TEXT NOT NULL,
  video_url VARCHAR(500),
  respondida BOOLEAN NOT NULL DEFAULT FALSE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
